import type { Metadata } from "next";
import { VercelToolbar } from "@vercel/toolbar/next";
import { Geist, Geist_Mono } from "next/font/google";
import config from "@/payload.config";
import "./globals.css";
import { Analytics as VercelAnalytics } from "@vercel/analytics/next";
import { Footer } from "@/components/footer";
import ReactLenis from "lenis/react";
import { getPayload } from "payload";
import { headers } from "next/headers";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const payload = await getPayload({ config });

	const { user } = await payload.auth({ headers: await headers() });
	const shouldMountToolbar =
		process.env.NODE_ENV === "development" || user?.email;

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<VercelAnalytics />
				<ReactLenis root>
					{children}
					<Footer />
				</ReactLenis>
				{shouldMountToolbar && <VercelToolbar />}
			</body>
		</html>
	);
}
